### ISSUE TITLE
Build instructions for Linux incorrect

### ISSUE THREAD

**Issue by sgehrman** [input-output-hk/cardano-sl#1921]
Could not perform step 1:

$ git clone git@github.com:input-output-hk/cardano-sl.git
Cloning into 'cardano-sl'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by domenkozar** [comment]
@sgehrman which instructions did you follow?

**Comment by tanzeelrana** [comment]
there are  so many problems with the linux installation instructions 
I also got the same error on one of my linux machines

**Comment by tanzeelrana** [comment]
I think it should be : git clone https://github.com/input-output-hk/cardano-sl.git

**Comment by domenkozar** [comment]
Aha, refers to https://cardanodocs.com/for-contributors/building-from-source/

**Comment by domenkozar** [comment]
@sgehrman fixed. Please reopen if you hit more issues.

**Comment by tanzeelrana** [comment]
Hi @domenkozar  https://cardanodocs.com/for-contributors/building-from-source/ link no longer exists. i get a 404. Also I am trying to build from source but am unable to due to the following error:

The command on https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

`$ nix-build -A cardano-sl-static --cores 0 --jobs 2 --no-build-output --out-link cardano-sl-1.0`

I get an error on --jobs 2 flag.

**Comment by denisshevchenko** [comment]
@tanzeelrana Try this:

```
nix-build -A cardano-sl-static --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0
```

**Comment by tanzeelrana** [comment]
That worked like a charm !! Cheers!

**Comment by domenkozar** [comment]
@denisshevchenko I thought I fixed that in the document yesterday?

**Comment by tanzeelrana** [comment]
@domenkozar  i see it is fixed in the documentation now. 

but now I am getting another error. 

Configuring clock-0.7.2...
Building clock-0.7.2...
Preprocessing library clock-0.7.2...
Clock.hsc:44:0: warning: "hsc_alignment" redefined
In file included from .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/System/Clock_hsc_make.c:1:0:
/nix/store/rzqyfil4xmja85w5sm13m107j1zm8d7s-ghc-8.0.2/lib/ghc-8.0.2/template-hsc.h:88:0: note: this is the location of the previous definition
 #define hsc_alignment(t...) \
 
hsc2hs: .stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/build/System/Clock_hsc_make: runProcess: runInteractiveProcess: exec: permission denied (Permission denied)

do i need to run the build process as root user ? that does not seem right to me.

**Comment by tanzeelrana** [comment]
Another Error : 

`stack build --ghc-options="-DGITREV=747e091ba72f81d2f0c73650a4f89fe93b09fc84 -Wwarn +RTS -A256m -n2m -RTS" --test --no-haddock-deps --bench --jobs=4 --flag cardano-sl:with-wallet --no-run-tests --no-run-benchmarks --fast  --allow-different-user cardano-sl-core

No packages found in snapshot which provide a "cpphs" executable, which is a build-tool dependency of "cardano-sl-core"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

cardano-sl-core-1.0.3: configure (lib)
Configuring cardano-sl-core-1.0.3...
Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The program 'cpphs' version >=1.19
is required but it could not be found.

--  While building package cardano-sl-core-1.0.3 using:`

**Comment by domenkozar** [comment]
You're not using Nix, so system libraries are missing.
