### ISSUE TITLE
Difference between Accounts and Wallets ? 

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2339]
Hi, 

Can anyone explain me what is the difference between wallets and accounts ? 
I am unable to wrap my head around the two in silo

I tried to look at the docs and was unable to find any reference.

**Comment by Martoon-00** [comment]
@tanzeelrana There are 3 levels of hierarchy - `wallet` contains `accounts`, `account` contains `addresses`. Model is described in official doc in more details: https://cardanodocs.com/technical/hd-wallets/#local-storage

Generally, motivation for distinguishing wallets and accounts is that one may want to have "pockets" in his wallet serving different purposes. For instance, I may want to have one account to pay for my house and another to spend money in grocery stores :smile:. To use those, I still need to remember only one mnemonics and password since they belong to the same wallet.

Although, AFAIU till this moment neither Daedalus nor one of our partners actually uses this feature, and they all keep one or several wallets, with 1 pre-created account each. Thus, multiple accounts feature is not properly supported yet and we strongly encourage not to use ATM.

**Comment by p-alik** [comment]
> Thus, multiple accounts feature is not properly supported yet and we strongly encourage not to use ATM.

Oh, that's very valuable information.
