### ISSUE TITLE
how to generate the cwID from passphrase ? where can i find that code in the repo ?

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2435]
How to generate the cwID from passphrase ? where can i find that code in the repo ?

Basically I want to know how cardano or daedalus generates the cwId for a wallet. Is it generated from the 12 word phrase ? I need to see where in the code is that part implemented. I am implementing a solution to speed up the restore function for my users and it is very crucial that I must understand the process of generating the cwId.

Basically I am looking to store that cwId instantly in my users profile and let the backend node recover the wallet on its own normal time. and keep the user shielded from the long callback wait time. and everytime the users come in between the restore process i tell them its still in progress 

If i can generate that cwId on the client side somehow since i already have the 12 word phrase on the client side I will be able to accomplish it without an issue :) 

I do see the details of it at : https://cardanodocs.com/cardano/addresses/#public-key-addresses
but I would like to know how exactly cardano/daedalus convert the 12 word mnemonic to this public address.

Thanks a million in advance :) 

Cheers

**Comment by tanzeelrana** [comment]
@CharlesHoskinson

**Comment by Martoon-00** [comment]
Yes, wallet id is generated from mnemonics. It is done in two stages:

* `EncryptedSecretKey` is generated from mnemonics
https://github.com/input-output-hk/cardano-sl/blob/aa482baf449352f8c2fbe86a34f61d150e4724a9/wallet/src/Pos/Util/BackupPhrase.hs#L73
This function requires spending password, but it doesn't affect resulting wallet id.

* `PublicKey` is derived from encrypted secret key, then address of that `PublicKey` is taken and this address is serialized and converted with `base58` encoding using bitcoin alphabet.
https://github.com/input-output-hk/cardano-sl/blob/aa482baf449352f8c2fbe86a34f61d150e4724a9/wallet/src/Pos/Wallet/Web/ClientTypes/Functions.hs#L50

Well, this seems tricky to implement out of the project.
Rework for restoring endpoint is really on the way, as temporal measure you might consider using `/api/wallets/new` endpoint to create wallet without restore in order to fetch wallet id, then delete wallet and do actual restore

**Comment by tanzeelrana** [comment]
aha ! crazy workaround @Martoon-00  !! super thanks gonna try this now and get back to u in a bit.

cheers !!
