### ISSUE TITLE
I want to send my own signed hexadecimal transaction. How should I send it? I didn't find the corresponding API

### ISSUE THREAD

**Issue by explosive77** [input-output-hk/cardano-sl#3058]
I want to send my own signed hexadecimal transaction. How should I send it? I didn't find the corresponding API

**Comment by refi93** [comment]
There isn't AFAIK. We reverse engineered it from Daedalus: https://github.com/vacuumlabs/cardano/blob/master/server/transactionSubmitter.js You can run your own transaction submission relay with this code snippet, but no guarantee that it will work "forever" since it isn't official. You can find the transaction serialization in the repo as well.

**Comment by refi93** [comment]
Regarding the transaction serialization itself, this is the best piece of documentation I found: https://github.com/input-output-hk/cardano-sl/blob/develop/docs/tx/binary-format.md This "docs" folder in general has many useful info.

**Comment by lhfly5201314** [comment]
Hi,@explosive77! Could u tell me how to sign an cardano transaction?
Is there any available API?

**Comment by guchenglin111** [comment]
https://github.com/input-output-hk/cardano-sl/issues/3647#issuecomment-424572542
