### ISSUE TITLE
How to use cardano-x509-certificates?

### ISSUE THREAD

**Issue by Coding-Jewelry** [input-output-hk/cardano-sl#3344]
Hi.

I installed and ran Cardano-SL wallet on my Ubuntu instance.
In order to see syncing progress of it, I have executed  "curl --cacert ca.crt -v https://localhost:8090/api/settings/sync/progress".   But it was not executed.
Probably some certificate files should be imported in it, I think.

So I have ran "stack exec -- cardano-x509-certificates --help"  to see the help, but it doesn't work also.
It shows me like:

Executable named cardano-x509-certificates not found on path:  [*** Paths ***]

How can I overcome this problem?

Also, I am seeing that there are several files (.crt, .key, .pem) in scripts/tls-files folder by default.
Can I use them on my instance?

Lastly, what I am not sure is which branch is stable and can be used in input-output-hk/cardano-sl repository.

Please give me a hint if you have any idea.
Thank you.

**Comment by KtorZ** [comment]
Hi, a few notes:

- In order to run `cardano-x509-certificates` you need to build `cardano-sl-tools` first (stack is fine for this purpose). Then, you can run the following command to generate fresh certificates:
```
$> stack exec -- cardano-x509-certificates \
  --server-out-dir . \
  --clients-out-dir . \
  -c ./lib/configuration.yaml \
  -k default
```

- If you run the node using stack directly, it gets its server and CA certificates from `scripts/tls-files/`. With cURL, you can use the `--cert` option passing along `scripts/tls-files/client.pem` to make a request (still with `--cacert scripts/tls-files/ca.crt`).

- If you run the node using `nix`, there should be a `state-***` folder (depending how you run it, could be `state-wallet-mainnet` or `state-demo` etc.). There's a `tls` folder in this state folder containing generated certificates used by the node or cluster of nodes.
