### ISSUE TITLE
Cannot build `2.0` wallet on MacOS Mojave (Nix problems)

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/cardano-sl#3944]
Hello!

I am trying to build a testnet wallet node from the `release/2.0.0` branch using this command:
```
nix-build -A connectScripts.testnet.wallet -o connect-wallet-to-testnet
```

And I am getting this response:
```
these derivations will be built:
  /nix/store/b1zd3vzra7hqzdfn82drn6mmpcwr4cal-topology-testnet.drv
  /nix/store/q8qz8v46vh2w1h1c9achqni2j0xpsl69-curl-wallet-testnet.drv
  /nix/store/x5bvsk8rhl9pkyghdhf6qg0ycaw1c1j4-wallet-connect-to-testnet.drv
these paths will be fetched (20.52 MiB download, 147.37 MiB unpacked):
  /nix/store/7scbdad0f86406j09bl1s5yxh8wyyczm-curl-7.59.0
  /nix/store/alwv94mfk8azmks4mk3in30r10hn5ch2-nghttp2-1.24.0-lib
  /nix/store/d97sldxf09fkqw19wrfvvqz0pgfq9hy2-libkrb5-1.15.2
  /nix/store/g59ii7p3720kd56sqz4szkwlxj8hmw44-curl-7.59.0-bin
  /nix/store/klxkzxdkv1ac64rkr9x0zk0bjjwh9qhi-cardano-sl-tools-static-2.0.0
  /nix/store/kr7vhi3jq1sdzj8bg4v07pmgdfvxyw53-libssh2-1.8.0
  /nix/store/x5rl1s3anx4am91bk35m0zmj89dxpk6y-cardano-sl-wallet-new-static-2.0.0
building '/nix/store/b1zd3vzra7hqzdfn82drn6mmpcwr4cal-topology-testnet.drv'...
dyld: Library not loade: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/fckg2z0w2fcqdd1rlpkhq3k7xp2bsbgg-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
builder for '/nix/store/b1zd3vzra7hqzdfn82drn6mmpcwr4cal-topology-testnet.drv' failed due to signal 6 (Abort trap: 6)
cannot build derivation '/nix/store/x5bvsk8rhl9pkyghdhf6qg0ycaw1c1j4-wallet-connect-to-testnet.drv': 1 dependencies couldn't be built
error: build of '/nix/store/x5bvsk8rhl9pkyghdhf6qg0ycaw1c1j4-wallet-connect-to-testnet.drv' failed
```

There's this known issue, describing problems of migrating Nix to Mojave: https://github.com/NixOS/nix/issues/2444

But also note that in November there was this PR: https://github.com/input-output-hk/cardano-sl/pull/3784 (@disassembler, @deepfire ?)

Among other things this PR migrated repo to the new revision of `nixpkgs`: https://github.com/input-output-hk/cardano-sl/pull/3784/files#diff-5d1f7887b883c9c823c016ba2636ced4

Currently I can see that branch `release/2.0.0` contains old version of the `nixpkgs-src.json` file: https://github.com/input-output-hk/cardano-sl/blob/release/2.0.0/nixpkgs-src.json

While `develop` contains new version since November: https://github.com/input-output-hk/cardano-sl/blob/develop/nixpkgs-src.json

I have no problems building wallet from the `develop` branch, but I would really like to build and test the 2.0 testnet wallet. I will greatly appreciate if this issue might be solved in this branch too.

Thank you!

**Comment by rvl** [comment]
Hi, thanks for the report. We can't bump nixpkgs on the stable branch because that would risk introducing defects that would delay the release.

If you just need to run the 2.0.0 testnet wallet on macOS, we have installers here: https://testnet.iohkdev.io/cardano/get-started/testnet-wallet/ (these are built on macOS pre-mojave).

If you would like to make changes and contribute a PR, then use the develop branch.

In other cases, then you could probably try backporting that PR on your local git clone, but I would recommend the above two solutions over that.

Does that help?

**Comment by vantuz-subhuman** [comment]
> If you just need to run the 2.0.0 testnet wallet on macOS, we have installers here

Ah, I was hoping to be able to run and test different kinds of node builds for testnet, like a wallet node, explorer node, etc. But I get it now that `nixpkgs` update is not stable yet 🤔 

Is there already a way to build the 2.0 version but from the develop branch (accepting the possible instability)? 

If no, then I prolly would have to try backporting the `nixpkgs` PR into the `release/2.0.0` branch locally and see if it might work )

**Comment by rvl** [comment]
The new nixpkgs revision _should_ be fine and stable. We have had no problems so far on `develop`. But it's just not a good idea to change the package set at a late stage in the release cycle.

I have rebased (backported) that PR branch to `release/2.0.0`.

https://github.com/input-output-hk/cardano-sl/compare/release/2.0.0...devops-1090-mojave-2.0.0

You could try this this branch and let us know if it builds on Mojave. It will take a little while to build because it's not cached by Hydra.

**Comment by vantuz-subhuman** [comment]
@rvl, it works! Successfully connected to testnet. Thank you very much! 👌🙂
