### ISSUE TITLE
Questions about query blocks

### ISSUE THREAD

**Issue by shenyaqi9527** [input-output-hk/cardano-sl#4267]
How to query block information through API

**Comment by erikd** [comment]
The explorer webapi is documented at: https://cardanodocs.com/technical/explorer/api/ 

However, I would advise against using the explorer in this repo (due to known bugs) and instead use the explorer in the https://github.com/input-output-hk/cardano-explorer/ respository which was coded to match the explorer documentation above as closely as possible.

**Comment by shenyaqi9527** [comment]
@erikd How to create addresses offline, sign some examples of broadcast transactions offline, preferably in Java, thanks.

**Comment by erikd** [comment]
In the `cardano-node` repository there is a CLI that allows the creation of a private/public key pairs and transactions (yes it works offline).

In the `cardano-explorer` repo there is an exectuable that allows a pre-created transaction to be published to the network.
